# Generated by Django 4.0.3 on 2022-03-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('secteurActivite', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to='profile/')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.entreprise')),
            ],
        ),
    ]
